### ISSUE TITLE
Warn people that we are not updating mods

### ISSUE THREAD

**Issue by Adaptivity** [ZeroLevels/modlist#734]
Can we add some kind of warning to this [link](http://modlist.mcf.li/submit/form) that we can't update mods? I'm tired of notifications about updating Ender IO to 1.8. Maybe this will help, maybe not. But this will make me happy a bit.

**Comment by GrygrFlzr** [comment]
Done, and I've also reworded 'Update Request' to 'Update Info' to make the point clearer.
