### ISSUE TITLE
What is wrong with this collection?

### ISSUE THREAD

**Issue by liach** [ZeroLevels/modlist#750]
This site seems to be no longer updated. What happened?

**Comment by ZeroLevels** [comment]
For me personally, I lost touch with it as I am not capable of fully taking over the backend, and even if I was, I wouldn't be proficient enough to consider advertisements.  If I don't use advertisements, then it earns me nothing, and I've got bills to pay and little time for learning.

I can't speak for Gryg, but until I am capable of making my own platform, CurseForge is superior anyways.  Even though I personally find it seriously lacks some features that I'd expect on such a platform, it still lists, hosts, and installs mods for you on a version-to-version basis.  While it only lists mods that work with Forge, overall its superior to the modlist.

I would like to maintain the list, but I just don't get anything out of it.  Unfortunately, I've hit a point where I need something out of it.
